server:
  port: 8761
  ssl:
    enabled: false
    key-alias: localhost_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: 12345678
    key-store-password: 12345678
#    enabled: true
#    key-alias: eureka_ssl
#    key-store: classpath:eureka-ssl.p12
#    key-store-type: PKCS12
#    key-password: 12345678
#    key-store-password: 12345678 

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    wait-time-in-ms-when-sync-empty: 0
  service-url:
      defaultZone: https://localhost:8761/eureka
#  tls:
#     enabled: true
#     key-store: classpath:local-ssl.p12
#     key-store-type: PKCS12
#     key-password: 12345678
#     key-store-password: 12345678
#     trust-store: classpath:local-ssl.p12
#     trust-store-type: PKCS12
#     trust-store-password: 12345678

